name: Issue Report
description: Report an issue
title: "[Issue]: "
labels: ["issue"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue report!
  - type: input
    id: plugin-version
    attributes:
      label: Plugin Version
      description: Which version of the plugin are you using?
      placeholder: ex. v0.0.1
    validations:
      required: true
  - type: input
    id: logseq-version
    attributes:
      label: Logseq Version
      description: Which version of Logseq are you using?
      placeholder: ex. v0.8.15
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - MacOS
        - Linux
        - Others
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen? Please include a screenshot if possible.
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
